/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTrainersRouteImport } from './routes/app/trainers'
import { Route as AppProgressRouteImport } from './routes/app/progress'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppPaymentsRouteImport } from './routes/app/payments'
import { Route as AppMentorsRouteImport } from './routes/app/mentors'
import { Route as AppLeaderboardRouteImport } from './routes/app/leaderboard'
import { Route as AppKidsRouteImport } from './routes/app/kids'
import { Route as AppHealthRouteImport } from './routes/app/health'
import { Route as AppGalleryRouteImport } from './routes/app/gallery'
import { Route as AppCommunityRouteImport } from './routes/app/community'
import { Route as AppCodexRouteImport } from './routes/app/codex'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppChallengesRouteImport } from './routes/app/challenges'
import { Route as AppCalorieRouteImport } from './routes/app/calorie'
import { Route as AppBrainFitnessRouteImport } from './routes/app/brain-fitness'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppAchievementsRouteImport } from './routes/app/achievements'
import { Route as AppAboutRouteImport } from './routes/app/about'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainersRoute = AppTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorsRoute = AppMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppKidsRoute = AppKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleryRoute = AppGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCodexRoute = AppCodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengesRoute = AppChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AppRoute,
} as any)
const AppCalorieRoute = AppCalorieRouteImport.update({
  id: '/calorie',
  path: '/calorie',
  getParentRoute: () => AppRoute,
} as any)
const AppBrainFitnessRoute = AppBrainFitnessRouteImport.update({
  id: '/brain-fitness',
  path: '/brain-fitness',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/about': typeof AppAboutRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/brain-fitness': typeof AppBrainFitnessRoute
  '/app/calorie': typeof AppCalorieRoute
  '/app/challenges': typeof AppChallengesRoute
  '/app/chat': typeof AppChatRoute
  '/app/codex': typeof AppCodexRoute
  '/app/community': typeof AppCommunityRoute
  '/app/gallery': typeof AppGalleryRoute
  '/app/health': typeof AppHealthRoute
  '/app/kids': typeof AppKidsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/mentors': typeof AppMentorsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/trainers': typeof AppTrainersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/about': typeof AppAboutRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/brain-fitness': typeof AppBrainFitnessRoute
  '/app/calorie': typeof AppCalorieRoute
  '/app/challenges': typeof AppChallengesRoute
  '/app/chat': typeof AppChatRoute
  '/app/codex': typeof AppCodexRoute
  '/app/community': typeof AppCommunityRoute
  '/app/gallery': typeof AppGalleryRoute
  '/app/health': typeof AppHealthRoute
  '/app/kids': typeof AppKidsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/mentors': typeof AppMentorsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/trainers': typeof AppTrainersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/about': typeof AppAboutRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/brain-fitness': typeof AppBrainFitnessRoute
  '/app/calorie': typeof AppCalorieRoute
  '/app/challenges': typeof AppChallengesRoute
  '/app/chat': typeof AppChatRoute
  '/app/codex': typeof AppCodexRoute
  '/app/community': typeof AppCommunityRoute
  '/app/gallery': typeof AppGalleryRoute
  '/app/health': typeof AppHealthRoute
  '/app/kids': typeof AppKidsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/mentors': typeof AppMentorsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/trainers': typeof AppTrainersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/app/about'
    | '/app/achievements'
    | '/app/admin'
    | '/app/brain-fitness'
    | '/app/calorie'
    | '/app/challenges'
    | '/app/chat'
    | '/app/codex'
    | '/app/community'
    | '/app/gallery'
    | '/app/health'
    | '/app/kids'
    | '/app/leaderboard'
    | '/app/mentors'
    | '/app/payments'
    | '/app/profile'
    | '/app/progress'
    | '/app/trainers'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/app/about'
    | '/app/achievements'
    | '/app/admin'
    | '/app/brain-fitness'
    | '/app/calorie'
    | '/app/challenges'
    | '/app/chat'
    | '/app/codex'
    | '/app/community'
    | '/app/gallery'
    | '/app/health'
    | '/app/kids'
    | '/app/leaderboard'
    | '/app/mentors'
    | '/app/payments'
    | '/app/profile'
    | '/app/progress'
    | '/app/trainers'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/app/about'
    | '/app/achievements'
    | '/app/admin'
    | '/app/brain-fitness'
    | '/app/calorie'
    | '/app/challenges'
    | '/app/chat'
    | '/app/codex'
    | '/app/community'
    | '/app/gallery'
    | '/app/health'
    | '/app/kids'
    | '/app/leaderboard'
    | '/app/mentors'
    | '/app/payments'
    | '/app/profile'
    | '/app/progress'
    | '/app/trainers'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trainers': {
      id: '/app/trainers'
      path: '/trainers'
      fullPath: '/app/trainers'
      preLoaderRoute: typeof AppTrainersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentors': {
      id: '/app/mentors'
      path: '/mentors'
      fullPath: '/app/mentors'
      preLoaderRoute: typeof AppMentorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kids': {
      id: '/app/kids'
      path: '/kids'
      fullPath: '/app/kids'
      preLoaderRoute: typeof AppKidsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gallery': {
      id: '/app/gallery'
      path: '/gallery'
      fullPath: '/app/gallery'
      preLoaderRoute: typeof AppGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/codex': {
      id: '/app/codex'
      path: '/codex'
      fullPath: '/app/codex'
      preLoaderRoute: typeof AppCodexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/challenges': {
      id: '/app/challenges'
      path: '/challenges'
      fullPath: '/app/challenges'
      preLoaderRoute: typeof AppChallengesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calorie': {
      id: '/app/calorie'
      path: '/calorie'
      fullPath: '/app/calorie'
      preLoaderRoute: typeof AppCalorieRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/brain-fitness': {
      id: '/app/brain-fitness'
      path: '/brain-fitness'
      fullPath: '/app/brain-fitness'
      preLoaderRoute: typeof AppBrainFitnessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAdminRoute: typeof AppAdminRoute
  AppBrainFitnessRoute: typeof AppBrainFitnessRoute
  AppCalorieRoute: typeof AppCalorieRoute
  AppChallengesRoute: typeof AppChallengesRoute
  AppChatRoute: typeof AppChatRoute
  AppCodexRoute: typeof AppCodexRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppGalleryRoute: typeof AppGalleryRoute
  AppHealthRoute: typeof AppHealthRoute
  AppKidsRoute: typeof AppKidsRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMentorsRoute: typeof AppMentorsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppTrainersRoute: typeof AppTrainersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAchievementsRoute: AppAchievementsRoute,
  AppAdminRoute: AppAdminRoute,
  AppBrainFitnessRoute: AppBrainFitnessRoute,
  AppCalorieRoute: AppCalorieRoute,
  AppChallengesRoute: AppChallengesRoute,
  AppChatRoute: AppChatRoute,
  AppCodexRoute: AppCodexRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppGalleryRoute: AppGalleryRoute,
  AppHealthRoute: AppHealthRoute,
  AppKidsRoute: AppKidsRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMentorsRoute: AppMentorsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppTrainersRoute: AppTrainersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
